#ifndef SEVENSEG_CONF_H
#define SEVENSEG_CONF_H

#define DIGIT_A_PORT PORTD
#define DIGIT_A_DIRECTION DDRD
#define DIGIT_A_PIN PD7
#define DIGIT_B_PORT PORTD
#define DIGIT_B_DIRECTION DDRD
#define DIGIT_B_PIN PD6

#define SEGMENT_A_PORT PORTC
#define SEGMENT_A_DIRECTION DDRC
#define SEGMENT_A_PIN PC0
#define SEGMENT_B_PORT PORTC
#define SEGMENT_B_DIRECTION DDRC
#define SEGMENT_B_PIN PC1
#define SEGMENT_C_PORT PORTC
#define SEGMENT_C_DIRECTION DDRC
#define SEGMENT_C_PIN PC2
#define SEGMENT_D_PORT PORTC
#define SEGMENT_D_DIRECTION DDRC
#define SEGMENT_D_PIN PC3
#define SEGMENT_E_PORT PORTC
#define SEGMENT_E_DIRECTION DDRC
#define SEGMENT_E_PIN PC4
#define SEGMENT_F_PORT PORTC
#define SEGMENT_F_DIRECTION DDRC
#define SEGMENT_F_PIN PC5
#define SEGMENT_G_PORT PORTC
#define SEGMENT_G_DIRECTION DDRC
#define SEGMENT_G_PIN PC6

#endif
